// 1장 walkthrough: order a player would follow. wrong:true answers one question wrong first.
[
 {intro:1,shot:'01-intro'},
 {bump:['circle','>']},
 {talk:'elhern',wrong:true,shotBefore:'02-festival',shotChoice:'03-elhern-question'},
 {talk:'sethr'},
 {talk:'chogger13'},
 {talk:'corto',wrong:true,shotBefore:'04-cauldron'},
 {check:()=>state.f.cortoGone,msg:'Corto wanders off from the cauldron'},
 {talk:'mel13',wrong:true},
 {talk:'livvi'},
 {talk:'kalton'},
 {check:()=>state.f.chase,msg:'the chase is on'},
 {talk:'pot',shotBefore:'05-shortcut',shotSay:{text:'튀었어요',name:'06-scald'}},
 {check:()=>state.f.burned,msg:'scalded'},
 {talk:'elhern',shotSay:{text:'검붉은',name:'07-severing'}},
 {check:()=>state.f.severed,msg:'Sethr turned away'},
 {talk:'story',wrong:true},
 {talk:'baker'},
 {talk:'corto',wrong:true,shotBuild:'08-build',shotSay:{text:'삼 년',name:'09-three-years'}},
 {check:()=>state.f.later,msg:'three years later'},
 {walkTo:['circle',6,8],then:'10-aro-at-16'},
 {talk:'melHome',wrong:true,shotBefore:'11-twins-house'},
 {talk:'corto'},
 {talk:'elhern'},
 {talk:'kalton'},
 {talk:'livvi'},
 {talk:'baker',wrong:true,shotBefore:'12-oven'},
 {check:()=>state.items.includes('탄 빵'),msg:'burnt bread'},
 {inspect:['circle',8,4],shot:'13-memory-stone'},
 {talk:'chogger',wrong:true,shotBefore:'14-fields'},
 {talk:'worker'},
 {talk:'herder',shotBefore:'15-roots-huts'},
 {inspect:['fields',2,9]},
 {talk:'gourds'},
 {check:()=>state.items.includes('물바가지')&&state.f.gourd,msg:'gourd taken'},
 {talk:'edge',shotBefore:'16-wilds-day'},
 {talk:'brosa',wrong:true,shotBefore:'17-brosa'},
 {check:()=>!npcAt(4,4),msg:'Corto is gone'},
 {talk:'kid',shotBefore:'18-elector'},
 {talk:'elector'},
 {talk:'melTree',wrong:true},
 {check:()=>state.f.stung,msg:'Melory stung'},
 {talk:'melHome',wrong:true,shotBefore:'19-fever'},
 {check:()=>state.f.night&&state.f.woke,msg:'day 31, night'},
 {talk:'melHome',wrong:true,shotBefore:'20-melory-doctor',shotSay:{text:'피가',name:'21-ghost'}},
 {check:()=>state.badges.length===C.WORDS.length,msg:'all words collected'},
 {walkTo:['circle',20,10],then:'22-night-circle'},
 {walkTo:['fields',12,12],then:'23-night-fields'},
 {talk:'edge',shotBuild:'24-flee-build'},
 {check:()=>state.f.done,msg:'chapter done'},
 {clock:26*3600e3},
 {inspect:['circle',8,4],shot:'25-stone-review'},
 {panel:1,shot:'26-log'},
]
