// 2장 walkthrough: order a player would follow. wrong:true answers one question wrong first.
[
 {intro:1,shot:'01-intro'},
 {talk:'nest'},
 {talk:'arraclid',wrong:true,shotBefore:'02-arraclid-dark',shotChoice:'03-arraclid-question'},
 {check:()=>state.f.arraclid&&state.f.day===1&&!C.ZONES.forest.dark(),msg:'the Arraclid left; day 1'},
 {walkTo:['forest',8,6],then:'04-forest-day'},
 {talk:'nest'},
 {talk:'berry',wrong:true,shotBefore:'05-berry'},
 {talk:'bark'},
 {check:()=>state.f.ate==='berry'&&state.badges.includes('굶다'),msg:'ate berries, learned 굶다'},
 {bump:['forest','E']},
 {talk:'raikerA',shotBefore:'06-raikers'},
 {check:()=>state.f.raikers&&state.f.day===2&&state.items.includes('나뭇잎 이불'),msg:'raikers left; day 2'},
 {talk:'raikerB'},
 {talk:'raikerC'},
 {talk:'berry',shotSay:{text:'토했어요',name:'07-vomit'}},
 {check:()=>state.f.ate==='sick',msg:'same food two days running → sick'},
 {talk:'nest'},
 {check:()=>state.f.day===3,msg:'day 3'},
 {talk:'jibbit',shotBefore:'08-jibbit'},
 {check:()=>state.items.includes('막대기')&&state.f.jibbit,msg:'stick; jibbit eaten'},
 {talk:'nest',wrong:true,shotSay:{text:'넷째 날',name:'09-day4-dark'},shotBuild:'10-build-lonely'},
 {check:()=>state.f.resolve&&state.f.day===4,msg:'resolved to leave'},
 {inspect:['forest',9,7],shot:'11-memory-stone'},
 {bump:['road','E']},
 {talk:'kaltonR',shotBefore:'12-road-camp'},
 {talk:'drummer'},
 {talk:'piper'},
 {talk:'carrier'},
 {inspect:['road',7,5]},
 {talk:'escort',wrong:true,shotBefore:'13-escort'},
 {check:()=>state.f.left,msg:'the procession left'},
 {talk:'ashes',wrong:true,shotBefore:'14-morning-ashes'},
 {check:()=>state.f.crust&&!state.items.includes('마른 빵 껍질'),msg:'crusts found and eaten'},
 {talk:'crodoc',shotBefore:'15-cro-welcome'},
 {talk:'kaltonC'},
 {talk:'toddler'},
 {talk:'womanB'},
 {talk:'grandma',wrong:true,shotBefore:'16-grandma'},
 {inspect:['cro',4,6]},
 {inspect:['cro',13,6]},
 {talk:'womanA',wrong:true,shotBefore:'17-kalton-home'},
 {check:()=>state.f.night,msg:'night falls on Cro'},
 {talk:'guard',wrong:true,shotBefore:'18-cro-night'},
 {check:()=>!!npcAt(11,12),msg:'the watchman blocks the bread rack'},
 {talk:'pen',shotBefore:'19-pen'},
 {check:()=>state.f.noise&&!npcAt(11,12),msg:'watchman drawn off to the pen'},
 {talk:'rack'},
 {talk:'line'},
 {check:()=>state.items.includes('옷')&&state.items.includes('신발'),msg:'clothes and shoes'},
 {walkTo:['cro',19,13],then:'20-stolen-clothes'},
 {talk:'flowerN'},
 {check:()=>state.f.hunt&&ZID==='cro'&&player.y<=3,msg:'morning: hunt begins, Handry back in the woods'},
 {talk:'hunter2'},
 {talk:'hunter',wrong:true,shotBefore:'21-hunters'},
 {talk:'huntress',wrong:true,shotBefore:'22-huntress',shotBuild:'23-build-east'},
 {check:()=>state.f.done&&!state.items.includes('막대기'),msg:'chapter done; stick put down'},
 {check:()=>state.badges.length===C.WORDS.length,msg:'all words collected'},
 {clock:26*3600e3},
 {inspect:['forest',9,7],shot:'24-stone-glow'},
 {look:true,shot:'90-look'},
 {panel:1,shot:'25-log'},
 // in-character review: with every word due, earlier chapters too, everyone who has a line asks it in their own voice, and it grades
 {reviewTour:Object.keys(C.ZONES),carry:1},
 // …and with nothing due, people with a line you haven't heard say it as plain talk (the word filled in, ungraded)
 {hearTour:Object.keys(C.ZONES)},
]
