// 3장 walkthrough: order a player would follow. wrong:true answers one question wrong first.
[
 {intro:1,shot:'01-intro'},
 {check:()=>['lineA','lineB','lineC','outcast','doctor','sharskin'].every(k=>!/(추방자|의사|샤스킨)/.test(C.NPC[k].name)),msg:'arrival labels do not reveal identities'},
 {talk:'sharskin'},
 {talk:'doctor'},
 {talk:'outcast'},
 {talk:'lineB'},
 {check:()=>state.badges.length===0&&!C.NPC.sharskin.script()[0].say.includes('추방자'),msg:'early talks keep neutral labels and do not skip the stew discovery'},
 {walkTo:['orovo',8,14],then:'02-channel'},
 {talk:'cauldron',wrong:true,shotBefore:'03-yard-dusk',shotChoice:'04-smell-question'},
 {talk:'sharskin',wrong:true,shotBefore:'05-sharskin-line'},
 {check:()=>state.badges.includes('줄을 서다')&&!state.items.includes('국 한 그릇'),msg:'waited in line first (book order: the line, then the bowl)'},
 {talk:'doctor',wrong:true,shotBefore:'06-doctor'},
 {check:()=>state.items.includes('국 한 그릇'),msg:'a bowl of stew'},
 {talk:'lineA'},
 {talk:'lineB'},
 {talk:'lineC'},
 {talk:'sharskin',wrong:true,shotBefore:'06a-sharskin-eat'},
 {check:()=>state.f.ate&&!state.items.includes('국 한 그릇'),msg:'Sharskin tasted it first; Handry ate'},
 {talk:'outcast',wrong:true},
 {talk:'ostel'},
 {talk:'ostel'},
 {check:()=>!usual(C.NPC.ostel).some(s=>/나는 오스텔|빨간 무늬/.test(s.say||'')),msg:'Ostel introduces himself only once'},
 {talk:'menic'},
 {talk:'villager'},
 {talk:'child',wrong:true,shotBefore:'07-child-riddle'},
 {talk:'child'},
 {talk:'child',wrong:true,shotChoice:'07a-quern-riddle'},
 {talk:'child',shotSay:{text:'여기까지',name:'07b-riddles-finished'}},
 {check:()=>state.f.riddles===3&&!C.NPC.child.script().some(s=>s.ask),msg:'three silent riddles, then a closing line'},
 {inspect:['orovo',7,8],shot:'08-memory-stone'},
 {inspect:['orovo',9,6]},
 {talk:'iblis',wrong:true,shotBefore:'09-iblis-speech'},
 {check:()=>ghosts.length===1,msg:'이블리스 walks off'},
 {check:()=>!!C.NPC.sharskinFire.walk,msg:'샤스킨 walks over to the fire'},
 {pause:0,shot:'09a-sharskin-walks'},
 {pause:3500},
 {check:()=>!C.NPC.sharskinFire.walk,msg:'…and arrives'},
 {talk:'sharskinFire',wrong:true,shotBefore:'10-night-fire',shotBuild:'11-build-budding'},
 {check:()=>state.f.budding&&C.NPC.sharskinFire.hide(),msg:'budding explained; Sharskin left for the tree'},
 {check:()=>!C.ZONES.orovo.warps['0,14'].lock()&&!C.NPC.doctor.after.includes('그릇 가져와'),msg:'west path opens with narration; doctor does not offer another bowl'},
 {walkTo:['orovo',10,9],then:'12-yard-day'},
 {walkTo:['tree',22,14],then:'12a-tree-east-edge'},
 {check:()=>ZID==='tree'&&player.x===22&&player.y===14&&!!C.ZONES.tree.warps['23,14'],msg:"west out of Orovo's fields lands on the clearing's east edge; east goes back"},
 {talk:'sharskinTree',shotBefore:'12b-stones-locked'},
 {walkTo:['tree',12,4]},
 {talk:'harboonW'},
 {check:()=>!state.items.includes('돌')&&!state.badges.includes('던지다')&&!state.f.harbW&&!state.f.nestDone&&C.NPC.harboonW.script().at(-1).say.includes('사냥꾼')&&C.NPC.nest.script()[0].say.includes('사냥꾼')&&C.questText().includes('사냥꾼'),msg:'hunter gates stones and climbing hints, including the nest shortcut'},
 {talk:'hunter',wrong:true,shotBefore:'13-harboon-tree',shotTap:'14-tap'},
 {talk:'sharskinTree',wrong:true},
 {check:()=>state.items.includes('돌'),msg:'a stone to throw'},
 {walkTo:['tree',12,4],then:'15-treetop'},
 {talk:'harboonW',wrong:true,shotBefore:'16-harboon'},
 {check:()=>state.f.harbW&&!state.items.includes('돌'),msg:'stone thrown, Harboon fled'},
 {talk:'harboonE'},
 {talk:'nest',wrong:true,shotBefore:'17-nest',shotBuild:'18-build-nest'},
 {check:()=>state.f.nestDone,msg:'nest broken'},
 {check:()=>{let n=0;return C.ZONES.tree.map.every((row,y)=>[...row].every((c,x)=>c!=='h'||(++n&&C.ZONES.tree.spots[x+','+y].includes('부서진'))))&&n===6},msg:'all six canopy nests now inspect as broken sticks'},
 {inspect:['tree',19,1],shot:'18a-broken-canopy'},
 {talk:'fallen',shotBefore:'19-fallen'},
 {talk:'iblisTree',wrong:true,shotSay:{text:'예측',name:'20-iblis-ghost'}},
 {check:()=>state.f.bargain&&state.f.refused&&!state.f.ghostOn,msg:'overheard the bargain; Iblis refused'},
 {talk:'sharskinTree'},
 {check:()=>state.f.warDone,msg:'eight days; the tree is cleared'},
 {talk:'hunter'},
 {check:()=>!C.NPC.hunter.after.includes('조심')&&C.NPC.lineB.talk()[0].say.includes('끝났어')&&C.NPC.lineA.pos()[0]===9&&C.NPC.lineB.pos()[1]===10,msg:'hunter changes after victory; feast queue disperses'},
 {talk:'doctor',shotBefore:'21-last-meal'},
 {talk:'lineB'},
 {check:()=>!C.NPC.sharskinFire.script().some(s=>/사람이 오스텔이에요|사람이 메닉이에요/.test(s.say||'')),msg:'the feast does not introduce already-met companions again'},
 {talk:'sharskinFire',shotBefore:'22-festival-night'},
 {check:()=>state.f.left,msg:'left Orovo with Sharskin'},
 {inspect:['orovo',11,8],shot:'22a-west-fire-out'},
 {inspect:['orovo',17,8],shot:'22b-east-fire-out'},
 {check:()=>['11,8','17,8'].every(k=>C.ZONES.orovo.spots[k].includes('불이 꺼졌어요')),msg:'both yard fires are out after departure'},
 {talk:'sharskinR',wrong:true,shotBefore:'23-road-camp'},
 {talk:'sevner'},
 {talk:'ostelR'},
 {talk:'sharskinR'},
 {talk:'menicR',wrong:true},
 {talk:'gbush'},
 {check:()=>state.items.includes('숲 음식'),msg:'gathered food'},
 {talk:'ostelR'},
 {check:()=>!C.NPC.ostelR.talk().some(s=>s.say.includes('덤불에 먹을 게'))&&C.NPC.gbush.script()[0].who==='…',msg:'empty bush has an object speaker; Ostel stops sending us there'},
 {talk:'sharskinR',wrong:true,shotSay:{text:'불꽃이 튀었어요',name:'24-bright-square'}},
 {check:()=>state.f.rp===2&&state.badges.includes('불을 피우다'),msg:'fire lit; night'},
 {talk:'sevner',shotBefore:'25-sevner'},
 {check:()=>state.f.rp===3,msg:'Sevner scared off'},
 {check:()=>C.REVIEW.filter(r=>r.by==='ostelR'&&r.when?.()).every(r=>!r.ask.includes('따뜻')&&!r.ask.includes('불 가까이')),msg:'second-camp fire lines are unavailable before its evening'},
 {walkTo:['road',19,8],then:'25a-east-huts-before-menic'},
 {check:()=>state.f.rp===3&&player.x===19&&player.y===8,msg:'east huts can be reached before Menic dies'},
 {talk:'ostelR'},
 {talk:'menicR',shotSay:{text:'머리뼈가',name:'26-blackout'}},
 {check:()=>state.f.menicDead&&!state.f.black&&state.f.rp===4,msg:'Menic killed; lights back'},
 {check:()=>C.NPC.menicR.hide()&&!C.NPC.menicBody.hide(),msg:'the living Menic is gone; his body lies there'},
 {talk:'ostelR',shotSay:{text:'메닉이 죽었어',name:'26a-ostel-menic'}},
 {check:()=>C.REVIEW.filter(r=>r.by==='ostelR'&&r.when?.()).every(r=>r.pre?.[0]?.say.includes('메닉이 죽었어')),msg:'every road review starts with Menic after his death'},
 {walkTo:['road',13,7],then:'27-aftermath'},
 {talk:'menicBody'},
 {talk:'bones',wrong:true,shotBefore:'28-burned-village'},
 {inspect:['road',20,3]},
 {inspect:['road',19,10]},
 {talk:'strut',wrong:true,shotBefore:'29-ruins'},
 {check:()=>{const p=C.NPC.sharskinR.pos();return p[0]===27&&p[1]===7},msg:'Sharskin, at the struts while you look, walks on to the hill'},
 {talk:'ostelR'},
 {talk:'sharskinR',shotBefore:'30-the-hill'},
 {check:()=>state.f.done,msg:'chapter done'},
 {check:()=>C.DONE.find(s=>s.expand).expand().filter(q=>q.w&&C.WORDS.includes(q.w)).every(q=>!C.REVIEW.some(r=>r.ask===q.ask)),msg:'end round uses distinct recollections, not repeated road dialogue'},
 {talk:'sharskinR'},
 {talk:'bones'},
 {talk:'strut'},
 {check:()=>state.badges.length===C.WORDS.length,msg:'all words collected'},
 {clock:26*3600e3},
 {inspect:['orovo',7,8],shot:'31-stone-glow'},
 {look:true,shot:'90-look'},
 {panel:1,shot:'32-log'},
 // in-character review: with every word due, earlier chapters too, everyone who has a line asks it in their own voice, and it grades
 {reviewTour:Object.keys(C.ZONES),carry:1},
 {talk:'ostelR',shotBefore:'30a-after-not-yet'},
 // A carried word at the stone gets a new example; a second visit avoids the last sentence and still grades it.
 {check:()=>{for(const L of Object.values(state.lv)){L.due=Date.now()+1e12;L.beat=null}for(const w of ['알','훔치다','동쪽'])state.lv[w].due=0;return true},msg:'only three memory words are due'},
 {inspect:['orovo',7,8],shot:'33-varied-memory'},
 {check:()=>{window.ch3MemoryFirst={...state.lastAsk};return ['알','훔치다','동쪽'].every(w=>state.lv[w].b>0&&state.lv[w].due>Date.now())&&!state.lastAsk['훔치다'].includes('우리 밭')},msg:'memory stone varies carried examples and grades all three words'},
 {talk:'villager'},
 {talk:'child'},
 {check:()=>{for(const w of ['알','훔치다','동쪽'])state.lv[w].due=0;return true},msg:'repeat the memory visit with the same due words'},
 {inspect:['orovo',7,8],shot:'34-varied-memory-again'},
 {check:()=>['알','훔치다','동쪽'].every(w=>state.lastAsk[w]!==window.ch3MemoryFirst[w]&&state.lv[w].due>Date.now()),msg:'second memory visit changes each sentence and still grades it'},
 // …and with nothing due, people with a line you haven't heard say it as plain talk (the word filled in, ungraded)
 {hearTour:Object.keys(C.ZONES)},
]
