// 3장 walkthrough: order a player would follow. wrong:true answers one question wrong first.
[
 {intro:1,shot:'01-intro'},
 {walkTo:['orovo',8,14],then:'02-channel'},
 {talk:'cauldron',wrong:true,shotBefore:'03-yard-dusk',shotChoice:'04-smell-question'},
 {talk:'sharskin',wrong:true,shotBefore:'05-sharskin-line'},
 {check:()=>state.badges.includes('줄을 서다')&&!state.items.includes('국 한 그릇'),msg:'waited in line first (book order: the line, then the bowl)'},
 {talk:'doctor',wrong:true,shotBefore:'06-doctor'},
 {check:()=>state.items.includes('국 한 그릇'),msg:'a bowl of stew'},
 {talk:'lineA'},
 {talk:'lineB'},
 {talk:'lineC'},
 {talk:'sharskin',wrong:true,shotBefore:'06a-sharskin-eat'},
 {check:()=>state.f.ate&&!state.items.includes('국 한 그릇'),msg:'Sharskin tasted it first; Handry ate'},
 {talk:'outcast',wrong:true},
 {talk:'ostel'},
 {talk:'menic'},
 {talk:'villager'},
 {talk:'child',wrong:true,shotBefore:'07-child-riddle'},
 {inspect:['orovo',7,8],shot:'08-memory-stone'},
 {inspect:['orovo',9,6]},
 {talk:'iblis',wrong:true,shotBefore:'09-iblis-speech'},
 {check:()=>ghosts.length===1,msg:'이블리스 walks off'},
 {check:()=>!!C.NPC.sharskinFire.walk,msg:'샤스킨 walks over to the fire'},
 {pause:0,shot:'09a-sharskin-walks'},
 {pause:3500},
 {check:()=>!C.NPC.sharskinFire.walk,msg:'…and arrives'},
 {talk:'sharskinFire',wrong:true,shotBefore:'10-night-fire',shotBuild:'11-build-budding'},
 {check:()=>state.f.budding&&C.NPC.sharskinFire.hide(),msg:'budding explained; Sharskin left for the tree'},
 {walkTo:['orovo',10,9],then:'12-yard-day'},
 {walkTo:['tree',22,14],then:'12a-tree-east-edge'},
 {check:()=>ZID==='tree'&&player.x===22&&player.y===14&&!!C.ZONES.tree.warps['23,14'],msg:"west out of Orovo's fields lands on the clearing's east edge; east goes back"},
 {talk:'hunter',wrong:true,shotBefore:'13-harboon-tree',shotTap:'14-tap'},
 {talk:'sharskinTree',wrong:true},
 {check:()=>state.items.includes('돌'),msg:'a stone to throw'},
 {walkTo:['tree',12,4],then:'15-treetop'},
 {talk:'harboonW',wrong:true,shotBefore:'16-harboon'},
 {check:()=>state.f.harbW&&!state.items.includes('돌'),msg:'stone thrown, Harboon fled'},
 {talk:'harboonE'},
 {talk:'nest',wrong:true,shotBefore:'17-nest',shotBuild:'18-build-nest'},
 {check:()=>state.f.nestDone,msg:'nest broken'},
 {talk:'fallen',shotBefore:'19-fallen'},
 {talk:'iblisTree',wrong:true,shotSay:{text:'예측',name:'20-iblis-ghost'}},
 {check:()=>state.f.bargain&&state.f.refused&&!state.f.ghostOn,msg:'overheard the bargain; Iblis refused'},
 {talk:'sharskinTree'},
 {check:()=>state.f.warDone,msg:'eight days; the tree is cleared'},
 {talk:'sharskinFire',shotBefore:'22-festival-night'},
 {check:()=>state.f.left,msg:'left Orovo with Sharskin'},
 {talk:'sharskinR',wrong:true,shotBefore:'23-road-camp'},
 {talk:'sevner'},
 {talk:'ostelR'},
 {talk:'sharskinR'},
 {talk:'menicR',wrong:true},
 {talk:'gbush'},
 {check:()=>state.items.includes('숲 음식'),msg:'gathered food'},
 {talk:'sharskinR',wrong:true,shotSay:{text:'불꽃이 튀었어요',name:'24-bright-square'}},
 {check:()=>state.f.rp===2&&state.badges.includes('불을 피우다'),msg:'fire lit; night'},
 {talk:'sevner',shotBefore:'25-sevner'},
 {check:()=>state.f.rp===3,msg:'Sevner scared off'},
 {talk:'ostelR'},
 {talk:'menicR',shotSay:{text:'머리뼈가',name:'26-blackout'}},
 {check:()=>state.f.menicDead&&!state.f.black&&state.f.rp===4,msg:'Menic killed; lights back'},
 {check:()=>C.NPC.menicR.hide()&&!C.NPC.menicBody.hide(),msg:'the living Menic is gone; his body lies there'},
 {walkTo:['road',13,7],then:'27-aftermath'},
 {talk:'menicBody'},
 {talk:'bones',wrong:true,shotBefore:'28-burned-village'},
 {inspect:['road',20,3]},
 {inspect:['road',19,10]},
 {talk:'strut',wrong:true,shotBefore:'29-ruins'},
 {check:()=>{const p=C.NPC.sharskinR.pos();return p[0]===27&&p[1]===7},msg:'Sharskin, at the struts while you look, walks on to the hill'},
 {talk:'ostelR'},
 {talk:'sharskinR',shotBefore:'30-the-hill'},
 {check:()=>state.f.done,msg:'chapter done'},
 {check:()=>state.badges.length===C.WORDS.length,msg:'all words collected'},
 {clock:26*3600e3},
 {inspect:['orovo',7,8],shot:'31-stone-glow'},
 {look:true,shot:'90-look'},
 {panel:1,shot:'32-log'},
 // in-character review: with every word due, earlier chapters too, everyone who has a line asks it in their own voice, and it grades
 {reviewTour:Object.keys(C.ZONES),carry:1},
 // …and with nothing due, people with a line you haven't heard say it as plain talk (the word filled in, ungraded)
 {hearTour:Object.keys(C.ZONES)},
]
