// 4장 walkthrough: order a player would follow. wrong:true answers one question wrong first.
[
 {intro:1,shot:'01-intro'},
 {talk:'sharE'},
 {talk:'ostel',wrong:true,shotBefore:'02-house-door'},
 {talk:'sharE',wrong:true,shotTap:'03-tap'},
 {check:()=>state.f.arrived&&state.badges.includes('조상'),msg:'arrived; 조상'},
 {inspect:['entry',5,9]},
 {walkTo:['entry',7,8],then:'04-airlock'},
 {inspect:['entry',9,7]},
 {bump:['entry','>']},
 {talk:'vet',shotBefore:'05-hall'},
 {check:()=>state.f.ate&&state.items.includes('조상의 음식'),msg:'ate a ration slab'},
 {talk:'yerke',wrong:true},
 {talk:'vernenE'},
 {talk:'bro1'},
 {talk:'bro2'},
 {talk:'old',wrong:true,shotBefore:'06-old-brother'},
 {bump:['entry','<']},
 {walkTo:['bridge',8,13],then:'07-console-room'},
 {talk:'holo',wrong:true,shotSay:{text:'은색 화살',name:'08-hologram'}},
 {talk:'house',wrong:true,shotBefore:'09-house-voice'},
 {talk:'frozen',shotBefore:'10-frozen-servant'},
 {talk:'ostel'},
 {talk:'sharB'},
 {talk:'root',shotBefore:'11-root'},
 {talk:'vet',wrong:true},
 {talk:'crack',shotBefore:'12-buried'},
 {check:()=>state.f.work,msg:'three days of work done'},
 {talk:'sharB',wrong:true,shotBefore:'13-sermon'},
 {talk:'young',wrong:true},
 {talk:'medbed',shotBefore:'14-medical-room'},
 {check:()=>state.f.trace,msg:'trace signal found'},
 {talk:'yerke',shotSay:{text:'까맣게',name:'15-yerke'}},
 {check:()=>state.f.yerke,msg:'Yerke dead'},
 {talk:'sharE',shotBefore:'16-raid-leave'},
 {check:()=>state.f.raid,msg:'raid done'},
 {talk:'melI',wrong:true,shotBefore:'17-melory-captive',shotSay:{text:'다운로드',name:'18-interrogation'}},
 {check:()=>state.f.interro,msg:'interrogation'},
 {talk:'ostelB',shotBefore:'19-held'},
 {talk:'melB'},
 {talk:'bunk'},
 {check:()=>state.f.night,msg:'night'},
 {walkTo:['entry',15,10],then:'20-night-hall'},
 {talk:'vernenB',wrong:true,shotBefore:'21-vernen-ostel'},
 {check:()=>state.f.vernen,msg:'Vernen dead, Ostel down'},
 {talk:'melB',wrong:true,shotBefore:'22-after-fight'},
 {check:()=>state.f.free&&state.items.includes('밧줄 조각'),msg:'rope cut'},
 {talk:'melBr',wrong:true,shotBefore:'23-hiding',shotSay:{text:'걸어 나왔어요',name:'24-servant-wakes'},shotBuild:'25-build-voice'},
 {check:()=>state.f.sharDead,msg:'Sharskin dead'},
 {walkTo:['bridge',10,5],then:'26-after-sharskin'},
 {talk:'sharBody'},
 {talk:'servantK'},
 {talk:'melBr',wrong:true,shotBuild:'27-build-refuse'},
 {check:()=>state.f.offer,msg:'cure declined; access shared'},
 {talk:'house',shotSay:{text:'제 목소리',name:'28-own-voice'}},
 {talk:'vet',shotBefore:'29-brothers-back'},
 {talk:'bro1'},
 {talk:'young'},
 {talk:'melBr',shotBefore:'30-finale'},
 {check:()=>state.f.done,msg:'chapter done'},
 {check:()=>state.badges.length===C.WORDS.length,msg:'all words collected'},
 {clock:26*3600e3},
 {inspect:['entry',2,5],shot:'31-stone-glow'},
 {look:true,shot:'90-look'},
 {panel:1,shot:'32-log'},
 // in-character review: with every word due, earlier chapters too, everyone who has a line asks it in their own voice, and it grades
 {reviewTour:Object.keys(C.ZONES),carry:1},
 // …and with nothing due, people with a line you haven't heard say it as plain talk (the word filled in, ungraded)
 {hearTour:Object.keys(C.ZONES)},
]
